### ISSUE TITLE
Readme Setup section could be improved to allow packaging for shipping builds

### ISSUE THREAD

**Issue by Vaei** [arnaud-jamin/Cog#23]
Note: None of these changes require any modification to Cog, only to the Readme.

Nothing from Cog is included in shipping builds, so you can't even use `#if ENABLE_COG` because it requires the `CogCommon.h` include but the module it belongs to (`Cog`) is not included because the `.Build.cs` omits it using `Target.Configuration != UnrealTargetConfiguration.Shipping` (as it should).

I use `!UE_BUILD_SHIPPING` instead for this reason.

In the readme you've also used includes that won't be available in shipping build. So I inherited the interfaces like so:

```cpp
class MYPROJECT_API AMyCharacter : public ACharacter
#if !UE_BUILD_SHIPPING
	, public ICogCommonDebugFilteredActorInterface
#endif
```

With this, my project packages in development build and also shipping build without any issues.

For `#if ENABLE_COG` to work, you would need to have a module that is included in shipping builds that does nothing other than define this. IMO it is not needed.

My recommendation: Drop `#if ENABLE_COG` from the Readme setup, use it internally but teach others to use `#if !UE_BUILD_SHIPPING` and add this to anything that is referenced (such as the interfaces).

I understand if you choose to extend the exclusion to something more than just `!UE_BUILD_SHIPPING` it might not be ideal, so that's up to you - in that case I would recommend adding a module to `Cog` named `CogShipping` that only defines this macro so it can be added to `.Build.cs` without `Target.Configuration != UnrealTargetConfiguration.Shipping`, which would just look like this:

```c#
        PublicDependencyModuleNames.Add("CogShipping");

        // Other Cog plugins can be added only for specific target configuration
        if (Target.Configuration != UnrealTargetConfiguration.Shipping)
        {
            PublicDependencyModuleNames.AddRange(new string[]
            {
                "CogAbility",
                "CogAI",
                "CogAll",
                "CogDebug",
                "CogEngine",
                "CogImgui",
                "CogInput",
                "CogWindow",
            });
        }
```

**Comment by arnaud-jamin** [comment]
Hello, 

Did you actually try to use the interfaces functionalities when using #if !UE_BUILD_SHIPPING ?
Because from what I tested it doesn't work.
Yes it compiles but it is as is the actor doesn't implement the interface, probably due to code generation not detecting it.

That's why I created the CogCommon module which contains minimal code.

In the sample CogCommon is included in shipping as you can see in this screenshot:
![image](https://github.com/arnaud-jamin/Cog/assets/13844285/fba06de9-c00c-424b-8c12-4b19d0981348)

CogCommon contains the header that defined ENABLE_COG. 
So in shipping build ENABLE_COG can be used.

That's why "CogCommon.h" is included here for example:
![image](https://github.com/arnaud-jamin/Cog/assets/13844285/d0aa8dfa-0779-463c-a3a7-333cc18e3f1b)

This way doesn't work for you ?

Thanks!

**Comment by Vaei** [comment]
Apologies, I missed `CogCommon` entirely, that explains a lot :)

**Comment by arnaud-jamin** [comment]
Cool, no problem!
