### ISSUE TITLE
ImGUI does not compile for Linux

### ISSUE THREAD

**Issue by infinstarlight** [arnaud-jamin/Cog#4]
I was attempting to build my project set to DebugGame for Linux (cross compiling via Windows) and I have 200 errors in Project Launcher with errors coming from ImGUI. Specifically, that "(Project)\Plugins\Cog\Source\ThirdParty\imgui\imgui.h(301,5): error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes"

I'm not sure if that is a command to be passed through the UAT but I need my project to be available for both Windows and Linux. I will do more investigating but any help would be appreciated! Thanks in advance.

**Comment by infinstarlight** [comment]
Quick update

I've tried compiling the plugins only for Windows but the compiler would still print out errors despite compiling for Linux. This may not be an issue for now thanks to tools like Proton but I would still prefer to have native builds for my projects. I found that ImGui has a #define of IMGUI_IMPL_API and is apparently used as the default so I'm not sure where exactly the issue is.

**Comment by arnaud-jamin** [comment]
Hello, 
I didn't try to compile it for Linux. Can you tell me what is your setup ?

**Comment by infinstarlight** [comment]
Windows 11 22H2
Unreal Engine 5.2 source build
Do you need hardware specs as well?

**Comment by arnaud-jamin** [comment]
I meant your setup on Windows to create a Linux build ? What do you use ?

**Comment by infinstarlight** [comment]
Oh sorry. Epic provides a tool chain to cross compile. 
https://docs.unrealengine.com/4.26/en-US/SharingAndReleasing/Linux/GettingStarted/
I have that installed on Windows and then target Linux from project launcher

**Comment by infinstarlight** [comment]
https://pastebin.com/0mGtgZRZ 

Here is my crash log

**Comment by arnaud-jamin** [comment]
I'm currently not setup to compile for Linux. 
__declspec(dllexport)  is a Windows keyword.

`The __declspec(dllexport) attribute exports the definition of a symbol through the dynamic symbol table when building DLL libraries`

It is present because of imconfig.h:

`//---- Define attributes of all API symbols declarations, e.g. for DLL under Windows
// Using Dear ImGui via a shared library is not recommended, because of function call overhead and because we don't guarantee backward nor forward ABI compatibility.
// DLL users: heaps and globals are not shared across DLL boundaries! You will need to call SetCurrentContext() + SetAllocatorFunctions()
// for each static/DLL boundary you are calling from. Read "Context and Memory Allocators" section of imgui.cpp for more details.
#define IMGUI_API __declspec( dllexport )
//#define IMGUI_API __declspec( dllimport )
`

I uncommented the '#define IMGUI_API __declspec( dllexport )' because the plugin CogImGui is a dll and we need other modules to call imgui function. 

I'm not sure how it is hanlded for Linux. 
You can try to change imconfig.h.

**Comment by infinstarlight** [comment]
I've continued to do some digging and was unsure about that, I will try it and report back!

**Comment by infinstarlight** [comment]
That still didn't work, I'm afraid

**Comment by AlbanCarpooler** [comment]
ah ok. my bad

**Comment by arnaud-jamin** [comment]
I updated the imgui library integration. It might fix your Linux build (I didn't try)
